/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcio Darlan
 */
public class tela_gui extends javax.swing.JFrame {

    private int funcao = 1;
    private double tempNum = 0;

    /**
     * Creates new form tela_gui2
     */
    public tela_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelHome = new javax.swing.JPanel();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        panelImc = new javax.swing.JPanel();
        labelRect1 = new org.edisoncor.gui.label.LabelRect();
        altura = new org.edisoncor.gui.label.LabelRect();
        peso = new org.edisoncor.gui.label.LabelRect();
        alturaText = new org.edisoncor.gui.textField.TextFieldRectIcon();
        pesoText = new org.edisoncor.gui.textField.TextFieldRectIcon();
        calcularImc = new org.edisoncor.gui.button.ButtonAction();
        resultadoImc = new javax.swing.JTextArea();
        cm = new org.edisoncor.gui.label.LabelRect();
        kg = new org.edisoncor.gui.label.LabelRect();
        panelPadrao = new javax.swing.JPanel();
        multiply = new org.edisoncor.gui.button.ButtonRound();
        resultado1 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        plus = new org.edisoncor.gui.button.ButtonRound();
        divid = new org.edisoncor.gui.button.ButtonRound();
        less = new org.edisoncor.gui.button.ButtonRound();
        equal = new org.edisoncor.gui.button.ButtonRound();
        num1 = new org.edisoncor.gui.button.ButtonRound();
        num2 = new org.edisoncor.gui.button.ButtonRound();
        num3 = new org.edisoncor.gui.button.ButtonRound();
        num4 = new org.edisoncor.gui.button.ButtonRound();
        num5 = new org.edisoncor.gui.button.ButtonRound();
        num6 = new org.edisoncor.gui.button.ButtonRound();
        num7 = new org.edisoncor.gui.button.ButtonRound();
        num8 = new org.edisoncor.gui.button.ButtonRound();
        num9 = new org.edisoncor.gui.button.ButtonRound();
        num0 = new org.edisoncor.gui.button.ButtonRound();
        clear = new org.edisoncor.gui.button.ButtonRound();
        del = new org.edisoncor.gui.button.ButtonRound();
        dot = new org.edisoncor.gui.button.ButtonRound();
        comma = new org.edisoncor.gui.button.ButtonRound();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        padrao = new javax.swing.JMenuItem();
        menuImc = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(340, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(340, 400));

        painelHome.setBackground(new java.awt.Color(255, 255, 255));

        labelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        labelCustom1.setForeground(new java.awt.Color(0, 0, 0));
        labelCustom1.setText("CALCULADORA");
        labelCustom1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout painelHomeLayout = new javax.swing.GroupLayout(painelHome);
        painelHome.setLayout(painelHomeLayout);
        painelHomeLayout.setHorizontalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        painelHomeLayout.setVerticalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHomeLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(labelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        panelImc.setVisible(false);
        panelImc.setBackground(new java.awt.Color(0, 0, 0));
        panelImc.setForeground(new java.awt.Color(255, 255, 255));
        panelImc.setPreferredSize(new java.awt.Dimension(340, 400));

        labelRect1.setBackground(new java.awt.Color(0, 0, 0));
        labelRect1.setText("IMC");
        labelRect1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        altura.setBackground(new java.awt.Color(0, 0, 0));
        altura.setText("Altura");
        altura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        peso.setBackground(new java.awt.Color(0, 0, 0));
        peso.setText("Peso");
        peso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        alturaText.setForeground(new java.awt.Color(0, 0, 0));
        alturaText.setCaretColor(new java.awt.Color(0, 0, 0));
        alturaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTextActionPerformed(evt);
            }
        });
        alturaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alturaTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alturaTextKeyTyped(evt);
            }
        });

        pesoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTextActionPerformed(evt);
            }
        });
        pesoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesoTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoTextKeyTyped(evt);
            }
        });

        calcularImc.setText("Calcular");
        calcularImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularImcActionPerformed(evt);
            }
        });

        resultadoImc.setVisible(false);
        resultadoImc.setEditable(false);
        resultadoImc.setColumns(20);
        resultadoImc.setRows(5);
        resultadoImc.setAutoscrolls(false);
        resultadoImc.setFocusable(false);
        resultadoImc.setMargin(new java.awt.Insets(20, 20, 0, 0));

        cm.setBackground(new java.awt.Color(0, 0, 0));
        cm.setText("cm");
        cm.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        kg.setBackground(new java.awt.Color(0, 0, 0));
        kg.setText("kg");
        kg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelImcLayout = new javax.swing.GroupLayout(panelImc);
        panelImc.setLayout(panelImcLayout);
        panelImcLayout.setHorizontalGroup(
            panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImcLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(resultadoImc)
                    .addGroup(panelImcLayout.createSequentialGroup()
                        .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesoText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(alturaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImcLayout.createSequentialGroup()
                                .addComponent(calcularImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGap(26, 26, 26)
                        .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImcLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        panelImcLayout.setVerticalGroup(
            panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImcLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calcularImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(resultadoImc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        panelPadrao.setVisible(false);
        panelPadrao.setBackground(new java.awt.Color(255, 255, 255));
        panelPadrao.setPreferredSize(new java.awt.Dimension(330, 400));

        multiply.setBackground(new java.awt.Color(0, 0, 0));
        multiply.setText("X");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        resultado1.setBackground(new java.awt.Color(0, 0, 0));
        resultado1.setForeground(new java.awt.Color(255, 255, 255));
        resultado1.setDescripcion("");
        resultado1.setLeft(java.lang.Boolean.FALSE);
        resultado1.setName("Resultado"); // NOI18N
        resultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado1ActionPerformed(evt);
            }
        });
        resultado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resultado1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resultado1KeyTyped(evt);
            }
        });

        plus.setBackground(new java.awt.Color(0, 0, 0));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        divid.setBackground(new java.awt.Color(0, 0, 0));
        divid.setText("/");
        divid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividActionPerformed(evt);
            }
        });

        less.setBackground(new java.awt.Color(0, 0, 0));
        less.setText("-");
        less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(0, 0, 0));
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        num1.setBackground(new java.awt.Color(0, 0, 0));
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(0, 0, 0));
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(0, 0, 0));
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(0, 0, 0));
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(0, 0, 0));
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(0, 0, 0));
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(0, 0, 0));
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(0, 0, 0));
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(0, 0, 0));
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num0.setBackground(new java.awt.Color(0, 0, 0));
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setText("CL");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        del.setBackground(new java.awt.Color(0, 0, 0));
        del.setText("<-");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(0, 0, 0));
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        comma.setBackground(new java.awt.Color(0, 0, 0));
        comma.setText(",");
        comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPadraoLayout = new javax.swing.GroupLayout(panelPadrao);
        panelPadrao.setLayout(panelPadraoLayout);
        panelPadraoLayout.setHorizontalGroup(
            panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPadraoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(panelPadraoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPadraoLayout.createSequentialGroup()
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPadraoLayout.createSequentialGroup()
                        .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPadraoLayout.createSequentialGroup()
                        .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPadraoLayout.createSequentialGroup()
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(less, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPadraoLayout.createSequentialGroup()
                                .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPadraoLayout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPadraoLayout.setVerticalGroup(
            panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPadraoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(less, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPadraoLayout.createSequentialGroup()
                        .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPadraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(402, 402, 402))
        );

        menuBar.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");

        padrao.setText("Padrao");
        padrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padraoActionPerformed(evt);
            }
        });
        jMenu1.add(padrao);

        menuImc.setText("IMC");
        menuImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImcActionPerformed(evt);
            }
        });
        jMenu1.add(menuImc);

        about.setText("Sobre");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu1.add(about);

        close.setBackground(new java.awt.Color(0, 0, 0));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu1.add(close);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelImc, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPadrao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelImc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTextDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDown1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTextDown1ActionPerformed

    private void buttonTextDown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDown2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTextDown2ActionPerformed

    private void buttonTextDown3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDown3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTextDown3ActionPerformed

    private void buttonTextDown4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDown4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTextDown4ActionPerformed

    private void buttonTextDown5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDown5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTextDown5ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void padraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padraoActionPerformed
        panelPadrao.setVisible(true);
        panelImc.setVisible(false);
        resultado1.requestFocus();
    }//GEN-LAST:event_padraoActionPerformed

    private void menuImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImcActionPerformed
        panelPadrao.setVisible(false);
        panelImc.setVisible(true);
        alturaText.requestFocus();
    }//GEN-LAST:event_menuImcActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        if (resultado1.getText().contains(".")){
            resultado1.requestFocus();
        } else {
            resultado1.setText(resultado1.getText()+".");
        }
        resultado1.requestFocus();
    }//GEN-LAST:event_dotActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        resultado1.setText(resultado1.getText()+"2");
        resultado1.requestFocus();
    }//GEN-LAST:event_num2ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        String resultado = resultado1.getText();
        String show = "";
        //char[] arr = new char[resultado.length()];
        System.out.println(resultado.length());
        for(int x = 0; x < resultado.length() - 1; x++) {
            //arr[x] = resultado.charAt(x);
            //JOptionPane.showMessageDialog(null, arr[x]);
            //show += String.valueOf(arr[x]);
            show += resultado.charAt(x);
            //System.out.println(arr[x]);
            System.out.println(resultado.charAt(x));
        }
        //for (char x : arr) {
            //    System.out.println(x);
            //}
        resultado1.setText(show);
        resultado1.requestFocus();
    }//GEN-LAST:event_delActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        resultado1.setText(resultado1.getText()+"1");
        resultado1.requestFocus();
    }//GEN-LAST:event_num1ActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        double convertido = 0;
        
        if (resultado1.getText().indexOf(".") == 0){
            convertido = Double.parseDouble("0" + resultado1.getText());
        } else {
            convertido = Double.parseDouble(resultado1.getText());
        }
        
        
        if (funcao == 1){
            resultado1.setText(String.valueOf(this.tempNum + convertido));
            JOptionPane.showMessageDialog(null, this.tempNum);
            funcao = 0;
            resultado1.requestFocus();
        } else if (funcao == 2){
            resultado1.setText(String.valueOf(this.tempNum - convertido));
            funcao = 0;
            resultado1.requestFocus();
        } else if (funcao == 3){

            resultado1.setText(String.valueOf(this.tempNum / convertido));
            funcao = 0;
            resultado1.requestFocus();
        } else if (funcao == 4){
            resultado1.setText(String.valueOf(this.tempNum * convertido));
            funcao = 0;
            resultado1.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Algo Deu Errado!");
            resultado1.setText("");
        }

    }//GEN-LAST:event_equalActionPerformed

    private void lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessActionPerformed
        funcao = 2;
        tempNum = Double.parseDouble(resultado1.getText());
        resultado1.setText("");
        resultado1.requestFocus();
    }//GEN-LAST:event_lessActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        funcao = 1;
        tempNum = Double.parseDouble(resultado1.getText());
        resultado1.setText("");
        resultado1.requestFocus();
    }//GEN-LAST:event_plusActionPerformed

    private void resultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado1ActionPerformed

    }//GEN-LAST:event_resultado1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        resultado1.setText("");
        funcao = 0;
        tempNum = 0;
        resultado1.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        resultado1.setText(resultado1.getText()+"0");
        resultado1.requestFocus();
    }//GEN-LAST:event_num0ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        resultado1.setText(resultado1.getText()+"9");
        resultado1.requestFocus();
    }//GEN-LAST:event_num9ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        resultado1.setText(resultado1.getText()+"8");
        resultado1.requestFocus();
    }//GEN-LAST:event_num8ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        resultado1.setText(resultado1.getText()+"7");
        resultado1.requestFocus();
    }//GEN-LAST:event_num7ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        resultado1.setText(resultado1.getText()+"6");
        resultado1.requestFocus();
    }//GEN-LAST:event_num6ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        resultado1.setText(resultado1.getText()+"5");
        resultado1.requestFocus();
    }//GEN-LAST:event_num5ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        resultado1.setText(resultado1.getText()+"4");
        resultado1.requestFocus();
    }//GEN-LAST:event_num4ActionPerformed

    private void commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaActionPerformed
        if (resultado1.getText().contains(".")){
            resultado1.requestFocus();
        } else {
            resultado1.setText(resultado1.getText()+".");
            resultado1.requestFocus();
        }
        resultado1.requestFocus();
    }//GEN-LAST:event_commaActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        resultado1.setText(resultado1.getText()+"3");
        resultado1.requestFocus();
    }//GEN-LAST:event_num3ActionPerformed

    private void pesoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextActionPerformed

    private void calcularImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularImcActionPerformed
        Double altura = Double.parseDouble(alturaText.getText());
        Double peso = Double.parseDouble(pesoText.getText());
        //IMC = Peso ÷ (Altura × Altura)
        resultadoImc.setVisible(true);
        if ((peso /(altura * altura)) < 18.6) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nAbaixo do Peso");
        } else if ((peso /(altura * altura)) > 18.6 && (peso /(altura * altura)) < 24.9) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nPeso Ideal");
        } else if ((peso /(altura * altura)) > 25 && (peso /(altura * altura)) < 29.9) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nLevemente Acima do Peso");
        } else if ((peso /(altura * altura)) > 30 && (peso /(altura * altura)) < 34.9) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nObesidade Grau 1");
        } else if ((peso /(altura * altura)) > 35 && (peso /(altura * altura)) < 39.9) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nObesidade Grau 2");
        } else if ((peso /(altura * altura)) > 40) {
            resultadoImc.setText("IMC: \n" + 
                    String.valueOf(peso /(altura * altura)) + 
                    "\nObesidade Grau 3");
        } else {
            resultadoImc.setText("Algo Saiu Errado");
        } 
        
        
    }//GEN-LAST:event_calcularImcActionPerformed

    private void dividActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividActionPerformed
        funcao = 3;
        tempNum = Double.parseDouble(resultado1.getText());
        resultado1.setText("");
        resultado1.requestFocus();
    }//GEN-LAST:event_dividActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        funcao = 4;
        tempNum = Double.parseDouble(resultado1.getText());
        resultado1.setText("");
        resultado1.requestFocus();
    }//GEN-LAST:event_multiplyActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        JOptionPane.showMessageDialog(null, "Developed By Marcio Darlan :p");
    }//GEN-LAST:event_aboutActionPerformed

    private void resultado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultado1KeyTyped
        String number = "0123456789.,";
        char typed = evt.getKeyChar();
        //if (number.indexOf(typed) < 0) {
         //   evt.consume();           
        //}
        if (!number.contains(String.valueOf(typed))) {
            evt.consume();
        } else if (resultado1.getText().contains(".")){
            evt.consume();
        }
        //System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_resultado1KeyTyped

    private void resultado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultado1KeyReleased
        if (String.valueOf(evt.getKeyChar()).equals(",")) {
            resultado1.setText(resultado1.getText().replace(",",  "."));
        }
    }//GEN-LAST:event_resultado1KeyReleased

    private void alturaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alturaTextKeyTyped
        String number = "0123456789.,";
        char typed = evt.getKeyChar();
        //if (number.indexOf(typed) < 0) {
         //   evt.consume();           
        //}
        if (!number.contains(String.valueOf(typed))) {
            evt.consume();
        } else if (alturaText.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_alturaTextKeyTyped

    private void alturaTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alturaTextKeyReleased
        if (String.valueOf(evt.getKeyChar()).equals(",")) {
            alturaText.setText(alturaText.getText().replace(",",  "."));
        }
    }//GEN-LAST:event_alturaTextKeyReleased

    private void pesoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoTextKeyReleased
        if (String.valueOf(evt.getKeyChar()).equals(",")) {
            pesoText.setText(pesoText.getText().replace(",",  "."));
        }
    }//GEN-LAST:event_pesoTextKeyReleased

    private void pesoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoTextKeyTyped
        //verificar(pesoText.getText());
        if (verificar(pesoText.getText(), String.valueOf(evt.getKeyChar())) == 0) {
            evt.consume();
        }
        char typed = evt.getKeyChar();
        //if (number.indexOf(typed) < 0) {
         //   evt.consume();           
        //}
        
    }//GEN-LAST:event_pesoTextKeyTyped

    private void alturaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private org.edisoncor.gui.label.LabelRect altura;
    private org.edisoncor.gui.textField.TextFieldRectIcon alturaText;
    private org.edisoncor.gui.button.ButtonAction calcularImc;
    private org.edisoncor.gui.button.ButtonRound clear;
    private javax.swing.JMenuItem close;
    private org.edisoncor.gui.label.LabelRect cm;
    private org.edisoncor.gui.button.ButtonRound comma;
    private org.edisoncor.gui.button.ButtonRound del;
    private org.edisoncor.gui.button.ButtonRound divid;
    private org.edisoncor.gui.button.ButtonRound dot;
    private org.edisoncor.gui.button.ButtonRound equal;
    private javax.swing.JMenu jMenu1;
    private org.edisoncor.gui.label.LabelRect kg;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelRect labelRect1;
    private org.edisoncor.gui.button.ButtonRound less;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuImc;
    private org.edisoncor.gui.button.ButtonRound multiply;
    private org.edisoncor.gui.button.ButtonRound num0;
    private org.edisoncor.gui.button.ButtonRound num1;
    private org.edisoncor.gui.button.ButtonRound num2;
    private org.edisoncor.gui.button.ButtonRound num3;
    private org.edisoncor.gui.button.ButtonRound num4;
    private org.edisoncor.gui.button.ButtonRound num5;
    private org.edisoncor.gui.button.ButtonRound num6;
    private org.edisoncor.gui.button.ButtonRound num7;
    private org.edisoncor.gui.button.ButtonRound num8;
    private org.edisoncor.gui.button.ButtonRound num9;
    private javax.swing.JMenuItem padrao;
    private javax.swing.JPanel painelHome;
    private javax.swing.JPanel panelImc;
    private javax.swing.JPanel panelPadrao;
    private org.edisoncor.gui.label.LabelRect peso;
    private org.edisoncor.gui.textField.TextFieldRectIcon pesoText;
    private org.edisoncor.gui.button.ButtonRound plus;
    private org.edisoncor.gui.textField.TextFieldRectBackground resultado1;
    private javax.swing.JTextArea resultadoImc;
    // End of variables declaration//GEN-END:variables

    private int verificar(String text, String valueOf) {
        String number = "0123456789.,";
        if (!number.contains(String.valueOf(valueOf))) {
            System.out.print(valueOf);
            return 0;
        } else if (text.contains(".")){
            return 0;
        }
        return 1;
    }

}
